USE Neptuno
GO

CREATE PROCEDURE spActualizarProducto
(
@IDPRODUCTO INT,
@NOMBREPRODUCTO NVARCHAR(40),
@CANTIDADPORUNIDAD NVARCHAR(20),
@PRECIOUNIDAD MONEY
)
AS
UPDATE Productos
SET
NombreProducto=@NOMBREPRODUCTO,
CantidadPorUnidad=@CANTIDADPORUNIDAD,
PrecioUnidad=@PRECIOUNIDAD
WHERE IdProducto=@IDPRODUCTO
RETURN
GO

CREATE PROCEDURE spEliminarProducto
(
@IDPRODUCTO INT
)
AS
DELETE FROM Productos
WHERE IdProducto=@IDPRODUCTO
RETURN
GO